apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: src-ip-ingress
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: src-ip-ingress
  template:
    metadata:
      labels:
        app: src-ip-ingress
    spec:
      containers:
      - name: src-ip-ingress
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 25m
          limits:
            cpu: 50m
