apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
     name: azure-files
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: azstaks1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
spec:
  storageClassName: azure-files
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
