apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisableServiceAccountAutoMount
metadata:
  name: pod-no-serviceaccount-automount
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
