apiVersion: v1
kind: ServiceAccount
metadata:
  name: omsagent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: omsagent-reader
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - nodes
  - namespaces
  - services
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: omsagentclusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: omsagent-reader
subjects:
- kind: ServiceAccount
  name: omsagent
  namespace: kube-system
